const actionType = {

    lOG_IN : "lOG_IN",
    lOG_IN_SUCCESS : "lOG_IN_SUCCESS",
    lOG_IN_FAILURE : "lOG_IN_FAILURE",
    LOG_OUT : "LOG_OUT",
    LOG_IN_METER_INFO : "LOG_IN_METER_INFO",
    LOG_IN_METER_INFO_SUCCESS : "LOG_IN_METER_INFO_SUCCESS",
    LOG_IN_METER_INFO_FAILURE : "LOG_IN_METER_INFO_FAILURE"
 }
 
 export default actionType ;